name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-image:
    runs-on: ubuntu-latest
    environment: assessment_env
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image from Hub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Run Container from Image
      run: docker run -d --name temp_container ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Copy Files from Local to Container
      run: docker cp ./path/to/local/files temp_container:/path/to/container/destination

    - name: Commit Changes to the Image
      run: docker commit temp_container ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Push Updated Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/myapp:latest

    - name: Clean up
      run: |
        docker rm -f temp_container
        docker system prune -f
    # - uses: actions/checkout@v4
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
